### ISSUE TITLE
gpu-cv-86

### ISSUE THREAD

**Issue by BS-98** [gmontamat/python-darknet-docker#1]
Hi,

could you add an gpu-cv-86 image in dockerhub? I would be grateful as I have RTX 3090.

**Comment by gmontamat** [comment]
of course!

**Comment by gmontamat** [comment]
I'm running the cc80 and cc86 jobs. Last time I've attempted to build it, I got errors but those may be solved with the ubuntu:20.04 base image update

**Comment by gmontamat** [comment]
@BS-98 I've pushed both gpu-cc86 and gpu-cv-cc86, let me know if it works for you
